_target_: pytorch_lightning.Trainer

# overfit_batches : 2
gpus: 2
strategy : "ddp"
# auto_select_gpus : True
# auto_lr_find : True
# overfit_batches : 8

min_epochs: 30 
max_epochs: 70

# progress_bar_refresh_rate: 1
# limit_train_batches : 0.05
resume_from_checkpoint: null
