model_type : models.ross.efficientdet
backbone : tf_df4
img_size : 1024
model :
  _target_ : src.modules.EfficientDetModule.EfficientDetModule
  model : 
    _target_ : icevision.${module.model_type}.model
    backbone :
      _target_ : icevision.${module.model_type}.backbones.${module.backbone}
      pretrained : 0
    num_classes : 2
    img_size : ${module.img_size} 
  learning_rate : 1e-4
