_target_ : src.modules.EfficientDetModule.EfficientDetModule
  model : 
    __target__ : models.ross.efficientdet.tf_lite0
      pretrained : True
      num_classes : 2
      image_size : 512
  learning_rate : 0.001
