model_type : models.ultralytics.yolov5
backbone : large_p6
img_size : 1024
pretrained : '/home.stud/kuntluka/DetectionFramework/epoch_007.ckpt'
model :
  _target_ : src.modules.YoloV5Module.YoloV5Module
  model : 
    _target_ : icevision.${module.model_type}.model
    backbone :
      _target_ : icevision.${module.model_type}.backbones.${module.backbone}
      pretrained : 1
    num_classes : 2
    img_size : ${module.img_size} 
  learning_rate : 1e-4
  optimizer : "adam"
  scheduler_patience : 5
  scheduler_factor : 0.2
  weight_decay : 1e-6