model_type : models.ultralytics.yolov5
backbone : lagrge_p6
img_size : 1024
model :
  _target_ : src.modules.YoloV5Module.YoloV5Module
  model : 
    _target_ : icevision.${module.model_type}.model
    backbone :
      _target_ : icevision.${module.model_type}.backbones.${module.backbone}
      pretrained : 0
    num_classes : 2
    img_size : ${module.img_size} 
  learning_rate : 1e-4