extract_patch:
  apply : True
  t:
    _target_ : src.utils.transforms.RandomCropNearBBoxFixed
    # target_size : [ ${module.img_size}, ${module.img_size} ]
    target_size : ${module.img_size}
    p : 1

pad_if_needed:
  apply : True
  t:
    _target_ : albumentations.PadIfNeeded
    min_height : ${module.img_size}
    min_width : ${module.img_size}
    border_mode : 0
    p : 1


horizontal_flip:
  apply: True
  t:
    _target_: albumentations.HorizontalFlip
    p : 0.5

vertical_flip:
  apply: True
  t:
    _target_ : albumentations.VerticalFlip
    p : 0.5

rotate:
  apply: True
  t:
    _target_ : albumentations.Rotate
    limit : 10 
    p : 0.3

affine_transform:
  apply : True
  t:
    _target_ : albumentations.Affine
    translate_percent : [-0.1, 0.1]
    p : 0.5

gaussian_blur:
  apply: True
  t:
    _target_ : albumentations.GaussianBlur
    blur_limit : [7, 31]
    p : 0.3

random_gamma:
  apply : True
  t:
    _target_ : albumentations.RandomGamma
    gamma_limit : [60, 140]
    p : 0.3
  