horizontal_flip:
  apply: True
  t:
    _target_: albumentations.HorizontalFlip
    p : 0.5

vertical_flip:
  apply: True
  t:
    _target_ : albumentations.VerticalFlip
    p : 0.5

rotate:
  apply: True
  t:
    _target_ : albumentations.SafeRotate
    limit : 5
    p : 0.3

affine_transform:
  apply : True
  t:
    _target_ : albumentations.Affine
    translate_percent : 1
    p : 0.5

gaussian_blur:
  apply: True
  t:
    _target_ : albumentations.GaussianBlur
    blur_limit : [11, 21]
    p : 0.3

random_gamma:
  apply : True
  t:
    _target_ : albumentations.RandomGamma
    gamma_limit : [80, 120]
    p : 0.3
  