defaults:
  - _self_
  - trainer: default.yaml
  - module : efficient_det.yaml
  - datamodule : dental_caries.yaml
  - logger : wandb.yaml
  # - logger : null
  - callbacks : callbacks.yaml
  - transforms : yolo_searched.yaml
  - experiment : train_patches.yaml

  - hparams_search: null

  # - logger: wandb # set logger here or use command line (e.g. `python run.py logger=wandb`)
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

seed : 42
name : null
ignore_warnings: False